# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import languagedetect_pb2 as languagedetect__pb2


class LanguageDetectStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLanguage = channel.unary_unary(
                '/LanguageDetect/GetLanguage',
                request_serializer=languagedetect__pb2.LanRequest.SerializeToString,
                response_deserializer=languagedetect__pb2.LanReply.FromString,
                )


class LanguageDetectServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLanguage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LanguageDetectServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLanguage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLanguage,
                    request_deserializer=languagedetect__pb2.LanRequest.FromString,
                    response_serializer=languagedetect__pb2.LanReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LanguageDetect', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LanguageDetect(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLanguage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LanguageDetect/GetLanguage',
            languagedetect__pb2.LanRequest.SerializeToString,
            languagedetect__pb2.LanReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
