// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: languagedetect.proto

package gprc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LanguageDetectClient is the client API for LanguageDetect service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LanguageDetectClient interface {
	GetLanguage(ctx context.Context, in *LanRequest, opts ...grpc.CallOption) (*LanReply, error)
}

type languageDetectClient struct {
	cc grpc.ClientConnInterface
}

func NewLanguageDetectClient(cc grpc.ClientConnInterface) LanguageDetectClient {
	return &languageDetectClient{cc}
}

func (c *languageDetectClient) GetLanguage(ctx context.Context, in *LanRequest, opts ...grpc.CallOption) (*LanReply, error) {
	out := new(LanReply)
	err := c.cc.Invoke(ctx, "/LanguageDetect/GetLanguage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LanguageDetectServer is the server API for LanguageDetect service.
// All implementations must embed UnimplementedLanguageDetectServer
// for forward compatibility
type LanguageDetectServer interface {
	GetLanguage(context.Context, *LanRequest) (*LanReply, error)
	mustEmbedUnimplementedLanguageDetectServer()
}

// UnimplementedLanguageDetectServer must be embedded to have forward compatible implementations.
type UnimplementedLanguageDetectServer struct {
}

func (UnimplementedLanguageDetectServer) GetLanguage(context.Context, *LanRequest) (*LanReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLanguage not implemented")
}
func (UnimplementedLanguageDetectServer) mustEmbedUnimplementedLanguageDetectServer() {}

// UnsafeLanguageDetectServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LanguageDetectServer will
// result in compilation errors.
type UnsafeLanguageDetectServer interface {
	mustEmbedUnimplementedLanguageDetectServer()
}

func RegisterLanguageDetectServer(s grpc.ServiceRegistrar, srv LanguageDetectServer) {
	s.RegisterService(&LanguageDetect_ServiceDesc, srv)
}

func _LanguageDetect_GetLanguage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanguageDetectServer).GetLanguage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LanguageDetect/GetLanguage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanguageDetectServer).GetLanguage(ctx, req.(*LanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LanguageDetect_ServiceDesc is the grpc.ServiceDesc for LanguageDetect service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LanguageDetect_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "LanguageDetect",
	HandlerType: (*LanguageDetectServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLanguage",
			Handler:    _LanguageDetect_GetLanguage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "languagedetect.proto",
}
